'use client';
import { useEffect, useRef, useState } from 'react';
import { Orbit, LayoutDashboard, Gamepad2, History, ArrowUpRight, ArrowDown, Trophy, Target, Zap, Cpu, HelpCircle, RotateCcw, ChevronRight, Sparkles, Shield } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { emptyBoard, drop, winner, chooseMove, legalMoves, type Board, type Difficulty } from '@/lib/game';
type Match = { id:string; result:'win'|'loss'|'draw'; difficulty:Difficulty; moves:number; date:string };
const modes = [{id:'easy',name:'Cadet',detail:'Find your rhythm'},{id:'medium',name:'Pilot',detail:'A worthy opponent'},{id:'hard',name:'Commander',detail:'Every move matters'}] as const;
const modeName = (d:Difficulty) => modes.find(m=>m.id===d)?.name || d;
function Navigation({view,setView}:{view:string;setView:(v:string)=>void}) {
 const {setOpenMobile}=useSidebar();
 return <Sidebar className="orbit-sidebar"><SidebarHeader><div className="brand"><span className="brand-icon"><Orbit size={28}/></span><span>ORBIT<span className="brand-four">FOUR</span></span></div><p className="brand-sub">HUMAN VS. MACHINE</p></SidebarHeader><SidebarContent><p className="nav-label">YOUR SPACE</p><SidebarMenu>{[{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'arena',label:'Play arena',icon:Gamepad2},{id:'history',label:'Match history',icon:History}].map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton isActive={view===item.id} onClick={()=>{setView(item.id);setOpenMobile(false)}} className="nav-item"><item.icon/><span>{item.label}</span>{view===item.id&&<span className="nav-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-note"><Cpu size={24}/><strong>Big brain. Zero bills.</strong><p>Your opponent thinks right in your browser. No credits. No subscriptions.</p><span className="local-badge"><i/> LOCAL AI ONLINE</span></div></SidebarContent><SidebarFooter><div className="profile"><span className="profile-icon">P1</span><div><strong>Earthling</strong><span>Human, probably.</span></div><Shield size={17}/></div></SidebarFooter></Sidebar>
}
export default function GameDashboard(){
 const [view,setView]=useState('dashboard');
 const [difficulty,setDifficulty]=useState<Difficulty>('medium');
 const [board,setBoard]=useState<Board>(emptyBoard());
 const [turn,setTurn]=useState<1|2>(1);
 const [result,setResult]=useState<'win'|'loss'|'draw'|null>(null);
 const [history,setHistory]=useState<Match[]>([]);
 const [loaded,setLoaded]=useState(false);
 const [storageIssue,setStorageIssue]=useState(false);
 const [help,setHelp]=useState(false);
 const [restart,setRestart]=useState(false);
 const [hover,setHover]=useState<number|null>(null);
 const [last,setLast]=useState<number|null>(null);
 const [hint,setHint]=useState<number|null>(null);
 const [announcement,setAnnouncement]=useState('Your move. Pick a column to drop an orb.');
 const recorded=useRef(false), turnLock=useRef(false);
 const moves=board.filter(Boolean).length;
 const wins=history.filter(m=>m.result==='win').length;
 const winRate=history.length?Math.round(wins/history.length*100):0;
 let streak=0;for(const m of history){if(m.result!=='win')break;streak++}
 const xp=history.reduce((sum,m)=>sum+(m.result==='win'?100:m.result==='draw'?40:20),0), level=Math.floor(xp/300)+1;
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('orbit-four-matches-v1')||'[]');if(Array.isArray(raw))setHistory(raw.filter(m=>m&&typeof m.id==='string'&&['win','loss','draw'].includes(m.result)&&['easy','medium','hard'].includes(m.difficulty)&&Number.isInteger(m.moves)&&m.moves>=7&&m.moves<=42&&typeof m.date==='string'&&!isNaN(Date.parse(m.date))).slice(0,200));}catch{setStorageIssue(true)}setLoaded(true)},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem('orbit-four-matches-v1',JSON.stringify(history))}catch{setStorageIssue(true)}},[history,loaded]);
 function finish(next:Board){const w=winner(next);const outcome=w.player?(w.player===1?'win':'loss'):legalMoves(next).length===0?'draw':null;if(!outcome)return false;setResult(outcome);setAnnouncement(outcome==='win'?'You win! Four in orbit.':outcome==='loss'?'NOVA wins this round. Ready for a rematch?':'A cosmic stalemate. The board is full.');if(!recorded.current){recorded.current=true;setHistory(h=>[{id:crypto.randomUUID(),result:outcome as Match['result'],difficulty,moves:next.filter(Boolean).length,date:new Date().toISOString()},...h].slice(0,200))}return true}
 function play(col:number){if(turnLock.current||turn!==1||result)return false;const next=drop(board,col,1);if(!next)return false;turnLock.current=true;setBoard(next.board);setLast(next.index);setHint(null);setHover(null);if(!finish(next.board)){setTurn(2);setAnnouncement('NOVA is plotting its next move…')}return true}
 useEffect(()=>{if(turn!==2||result)return;const timer=setTimeout(()=>{const col=chooseMove(board,2,difficulty),next=drop(board,col,2);if(next){setBoard(next.board);setLast(next.index);if(!finish(next.board)){setTurn(1);setAnnouncement(`NOVA chose column ${col+1}. Your move.`)}}turnLock.current=false},450);return()=>clearTimeout(timer)},[turn,board,result,difficulty]);
 function newGame(){setBoard(emptyBoard());setTurn(1);setResult(null);setLast(null);setHint(null);setHover(null);recorded.current=false;turnLock.current=false;setAnnouncement('Your move. Pick a column to drop an orb.');setRestart(false);setView('arena')}
 function requestNew(){if(moves&&!result)setRestart(true);else newGame()}
 function showHint(){if(turn===1&&!result){const col=chooseMove(board,1,'hard');setHint(col);setAnnouncement(`Try column ${col+1}. Build a threat or block NOVA.`)}}
 const toolState=useRef({board,turn,result,play,newGame,moves});
 toolState.current={board,turn,result,play,newGame,moves};
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const snapshot=()=>{const s=toolState.current;return{board:s.board,turn:s.turn===1?'human':'NOVA',result:s.result,moves:s.moves,legalColumns:legalMoves(s.board).map(c=>c+1)}};
  const settled=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(snapshot()))));
  const tools:Tool[]=[{name:'read_orbit_match',description:'Read the current Orbit Four board, whose turn it is, and legal columns.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:snapshot},{name:'drop_orbit_orb',description:'Play the human turn by dropping a cyan orb in a column from 1 to 7.',inputSchema:{type:'object',properties:{column:{type:'integer',minimum:1,maximum:7}},required:['column'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const c=(input as {column?:unknown})?.column;if(typeof c!=='number'||!Number.isInteger(c)||c<1||c>7)throw new Error('Column must be an integer from 1 to 7.');if(!toolState.current.play(c-1))throw new Error('Move unavailable: wait for your turn, choose an open column, or start a new match.');return settled()}},{name:'start_orbit_match',description:'Start a new match when the board is empty or the previous match has ended. Refuses to discard an unfinished match.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{const s=toolState.current;if(s.moves&&!s.result)throw new Error('Finish the active match or restart it using the visible confirmation.');s.newGame();return settled()}}];
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
  return()=>lifecycle.abort();
 },[]);
 const winning=winner(board).cells;
 const navTitle=view==='dashboard'?'Dashboard':view==='arena'?'Play arena':'Match history';
 const recentTable=<Table className="match-table"><TableHeader><TableRow><TableHead>RESULT</TableHead><TableHead>OPPONENT</TableHead><TableHead>MOVES</TableHead><TableHead>PLAYED</TableHead></TableRow></TableHeader><TableBody>{history.slice(0,view==='history'?200:4).map(m=><TableRow key={m.id}><TableCell><span className={`result-pill ${m.result}`}>{m.result==='win'?'Victory':m.result==='loss'?'Defeat':'Draw'}</span></TableCell><TableCell>NOVA <span className="dim">/ {modeName(m.difficulty)}</span></TableCell><TableCell>{m.moves}</TableCell><TableCell className="dim">{new Date(m.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</TableCell></TableRow>)}</TableBody></Table>;
 return <SidebarProvider style={{'--sidebar-width':'15rem'} as React.CSSProperties}><Navigation view={view} setView={setView}/><main className="main-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-toggle"/><span>Your space</span><ChevronRight size={14}/><strong>{navTitle}</strong></div><div className="top-actions"><span className="free-label"><i/> Free to play</span><button className="help-button" onClick={()=>setHelp(true)} aria-label="How to play"><HelpCircle size={19}/></button><span className="tiny-avatar">P1</span></div></header><div className="page-wrap"><div className="page-heading"><div><p className="eyebrow">{view==='history'?'FLIGHT RECORDER':'HUMAN INSTINCT. MACHINE LOGIC.'}</p><h1>{view==='dashboard'?'Your next move starts here.':view==='arena'?'Make some space.':'Every orbit tells a story.'}</h1><p className="subtitle">{view==='history'?'Your completed matches, saved on this device.':'Connect four. Outsmart NOVA. One more round.'}</p></div><button className="outline-button how" onClick={()=>setHelp(true)}><HelpCircle size={16}/> How to play</button></div>
 {storageIssue&&<p className="storage-notice" role="status">This browser can’t save your history. You can still play this session.</p>}
 {view!=='arena'&&<section className="stats-grid" aria-label="Your statistics">{[{label:'MATCHES PLAYED',value:history.length,sub:'Every round is a fresh start',icon:Gamepad2},{label:'VICTORIES',value:wins,sub:'Humanity thanks you',icon:Trophy},{label:'WIN RATE',value:`${winRate}%`,sub:history.length?'Across all difficulties':'Your first win is out there',icon:Target},{label:'CURRENT STREAK',value:streak,sub:streak?'Keep the orbit going':'Let’s start something',icon:Zap}].map((s,i)=><div className="stat-card" key={s.label}><div className="stat-top"><span>{s.label}</span><s.icon size={17}/></div><strong className={i===1?'cyan-text':''}>{s.value}</strong><p>{s.sub}</p></div>)}</section>}
 {view!=='history'&&<div className="play-layout"><section className="arena-card"><div className="arena-title"><div><span className="arena-kicker"><i/> {result?'MATCH COMPLETE':'LIVE ARENA'}</span><h2>Orbit Four <span>01</span></h2></div><span className="mode-tag">{modeName(difficulty)}</span></div><div className="players"><div className={`player ${turn===1&&!result?'active':''}`}><span className="orb-icon human"/><div><strong>You</strong><span>The unpredictable one</span></div><span className="player-tag">P1</span></div><span className="versus">VS</span><div className={`player ai-player ${turn===2&&!result?'active':''}`}><span className="ai-icon"><Cpu size={21}/></span><div><strong>NOVA</strong><span>{turn===2&&!result?'Thinking…':'A little too confident'}</span></div><span className="player-tag">AI</span></div></div>
 <div className="board-shell"><div className="column-buttons">{Array.from({length:7},(_,c)=><button key={c} aria-label={`Drop orb in column ${c+1}`} disabled={turn===2||!!result||board[c]!==0} className={hint===c?'hint-column':''} onMouseEnter={()=>setHover(c)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(c)} onBlur={()=>setHover(null)} onClick={()=>play(c)}><ArrowDown size={17}/><span>{c+1}</span></button>)}</div><div className="game-board" role="group" aria-label={`Game board. ${moves} orbs played. ${announcement}`}>{board.map((cell,i)=>{const landing=hover===i%7&&!cell&&(i>=35||board[i+7]!==0);return <span key={i} className={`board-cell ${cell===1?'human':cell===2?'machine':''} ${winning.includes(i)?'winning':''} ${last===i?'just-dropped':''} ${landing&&turn===1&&!result?'ghost':''}`} aria-label={`Row ${Math.floor(i/7)+1}, column ${i%7+1}: ${cell===1?'you':cell===2?'NOVA':'empty'}`}><span/>{winning.includes(i)&&<Sparkles size={21}/>}</span>})}</div><div className="board-bottom"><span><i className="legend-dot cyan"/> You</span><span><i className="legend-dot violet"/> NOVA</span><span className="move-count">MOVE {String(moves).padStart(2,'0')} / 42</span></div></div>
 <div className={`turn-strip ${result?'finished':''}`}><div><span className={`status-dot ${turn===2?'thinking':''}`}/><p role="status" aria-live="polite">{announcement}</p></div>{result?<button className="small-primary" onClick={newGame}>Rematch <ArrowUpRight size={16}/></button>:<button className="text-button" disabled={turn===2} onClick={showHint}><Sparkles size={15}/> Hint</button>}</div></section>
 <aside className="arena-aside"><section className="panel opponent-panel"><div className="section-label"><Cpu size={17}/> MEET YOUR OPPONENT</div><div className="nova-heading"><span className="nova-symbol"><Orbit size={39}/></span><div><h2>NOVA<span className="cyan-text">.</span></h2><span className="ai-caption">ONBOARD ARTIFICIAL INTELLIGENCE</span></div></div><blockquote>“I’ve calculated every outcome.<br/>Except whatever you’re about to do.”</blockquote><div className="difficulty-label"><strong>Choose your challenge</strong></div><RadioGroup value={difficulty} onValueChange={v=>{if(!moves||result)setDifficulty(v as Difficulty)}} disabled={moves>0&&!result} aria-label="AI difficulty" className="difficulty-options">{modes.map((m,i)=><label htmlFor={m.id} key={m.id} className={`difficulty-option ${difficulty===m.id?'selected':''}`}><RadioGroupItem id={m.id} value={m.id}/><span><strong>{m.name}</strong><small>{m.detail}</small></span><span className="difficulty-bars">{[0,1,2].map(b=><i key={b} className={b<=i?'on':''}/>)}</span></label>)}</RadioGroup>{moves>0&&!result&&<p className="locked-note">Difficulty stays fixed until this match ends.</p>}<Button onClick={requestNew} className="new-game"><RotateCcw size={17}/> {moves&&!result?'Restart match':'New match'}<ArrowUpRight size={18}/></Button><div className="cost-note"><Shield size={14}/> No API key. No paywall. Just play.</div></section>
 <section className="rank-panel"><div className="rank-top"><span className="rank-badge"><Zap size={23}/></span><div><span className="section-label">YOUR FLIGHT RANK</span><h3>{level===1?'Space cadet':level<4?'Orbital pilot':'Star commander'}</h3></div><span className="level">LV {level}</span></div><div className="xp-label"><span>{xp%300} / 300 XP</span><span>Next level</span></div><Progress value={xp%300/3} aria-label="Progress to next flight rank"/><p>+100 XP per win · +40 per draw · +20 per loss</p></section><div className="tip"><span>↗</span><p><strong>A little orbital wisdom</strong>Own the center. It gives you more ways to connect—and fewer places for NOVA to hide.</p></div></aside></div>}
 {view!=='arena'&&<section className="history-panel"><div className="history-heading"><div><h2>{view==='history'?'Match history':'Recent encounters'}</h2><p>Your battles against the machine.</p></div>{view==='dashboard'&&<button className="text-button" onClick={()=>setView('history')}>View all <ArrowUpRight size={16}/></button>}</div>{history.length?recentTable:<div className="empty-history"><History size={25}/><div><strong>Your story is still unwritten.</strong><p>Finish your first match to put it on the board.</p></div><button className="text-button" onClick={()=>setView('arena')}>Enter arena <ArrowUpRight size={17}/></button></div>}</section>}
 <footer className="page-footer"><span><Orbit size={14}/> ORBIT FOUR</span><p>Built for the joy of “one more game.”</p><span>Local AI · History on this device</span></footer></div></main>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>Four in a row. Infinite rematches.</DialogTitle><DialogDescription>You’re cyan. NOVA is violet. Connect four orbs horizontally, vertically, or diagonally before the AI does.</DialogDescription></DialogHeader><ol className="rules"><li><strong>Pick a column.</strong> Click its arrow or tab to it and press Enter. Your orb falls into the lowest empty spot.</li><li><strong>Watch NOVA.</strong> The AI responds after each move. Block its lines while building yours.</li><li><strong>Claim your orbit.</strong> Four connected orbs win. A full board without a winner is a draw.</li></ol><p className="dialog-note">Cadet leaves room to experiment. Pilot looks ahead. Commander searches deeper. This is a local strategy AI—not a paid chatbot.</p><Button className="new-game" onClick={()=>setHelp(false)}>Let’s play <ArrowUpRight size={17}/></Button></DialogContent></Dialog>
 <Dialog open={restart} onOpenChange={setRestart}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>Start a fresh orbit?</DialogTitle><DialogDescription>Your current unfinished match won’t count toward your stats.</DialogDescription></DialogHeader><Button className="new-game" onClick={newGame}>Restart match</Button><Button variant="outline" onClick={()=>setRestart(false)}>Keep playing</Button></DialogContent></Dialog>
 </SidebarProvider>
}


