export type Board = number[];
export type Difficulty = 'easy'|'medium'|'hard';
export const emptyBoard = ():Board => Array(42).fill(0);
const order=[3,2,4,1,5,0,6];
export const legalMoves=(b:Board)=>order.filter(c=>b[c]===0);
export function drop(b:Board,c:number,p:number):{board:Board;index:number}|null{if(!Number.isInteger(c)||c<0||c>6||b[c])return null;for(let r=5;r>=0;r--){const i=r*7+c;if(!b[i]){const next=[...b];next[i]=p;return{board:next,index:i}}}return null}
export function winner(b:Board):{player:number;cells:number[]}{for(let r=0;r<6;r++)for(let c=0;c<7;c++){const p=b[r*7+c];if(!p)continue;for(const [dr,dc]of [[0,1],[1,0],[1,1],[1,-1]]){const cells=[];for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>5||cc<0||cc>6||b[rr*7+cc]!==p)break;cells.push(rr*7+cc)}if(cells.length===4)return{player:p,cells}}}return{player:0,cells:[]}}
function evaluate(b:Board,p:number){let score=0;for(let r=0;r<6;r++){if(b[r*7+3]===p)score+=6;else if(b[r*7+3]===3-p)score-=6}for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){let own=0,opp=0,valid=true;for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr>5||cc<0||cc>6){valid=false;break}const v=b[rr*7+cc];if(v===p)own++;if(v===3-p)opp++}if(valid){if(!opp)score+=[0,1,8,65,10000][own];if(!own)score-=[0,1,10,80,10000][opp]}}return score}
function search(b:Board,depth:number,alpha:number,beta:number,turn:number,p:number):number{const w=winner(b).player;if(w)return w===p?100000+depth:-100000-depth;const legal=legalMoves(b);if(!legal.length)return 0;if(!depth)return evaluate(b,p);let value=turn===p?-Infinity:Infinity;for(const c of legal){const s=search(drop(b,c,turn)!.board,depth-1,alpha,beta,3-turn,p);if(turn===p){value=Math.max(value,s);alpha=Math.max(alpha,value)}else{value=Math.min(value,s);beta=Math.min(beta,value)}if(alpha>=beta)break}return value}
export function chooseMove(b:Board,p:number,difficulty:Difficulty):number{const legal=legalMoves(b);if(!legal.length||winner(b).player)return -1;for(const c of legal){if(winner(drop(b,c,p)!.board).player===p)return c}if(difficulty!=='easy')for(const c of legal){if(winner(drop(b,c,3-p)!.board).player===3-p)return c}if(difficulty==='easy'&&Math.random()<0.5)return legal[Math.floor(Math.random()*legal.length)];const depth=difficulty==='hard'?5:difficulty==='medium'?3:1;let best=-Infinity,choice=legal[0];for(const c of legal){const s=search(drop(b,c,p)!.board,depth-1,-Infinity,Infinity,3-p,p);if(s>best){best=s;choice=c}}return choice}
